alias l='ls -F'
alias ll='ls -lF'
alias la='ls -aF'
alias lla='ls -laF'

alias g='git'
alias gad='git add'
alias gb='git branch'
# alias gc='git commit -v'
alias gco='git commit -v'
alias gfe='git fetch'
alias gmv='git mv'
alias gs='git status -s --untracked-files=no'
alias gst='git status --untracked-files=no'
alias gsh='git show -s'
alias gps='git push'
alias gpl='git pull'
alias gre='git restore'
alias gres='git restore'
alias gch='git checkout'
alias gsw='git switch'
